# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ChatKit' do

pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'MJRefresh'
pod 'Masonry'
pod 'SDWebImage'
pod 'FMDB'
pod 'UITableView+FDTemplateLayoutCell'
end

