target 'ChatKit-OC' do
  platform :ios , '8.0'
  inhibit_all_warnings!

  #=========================================================
  #======================== Lib Dependency =================
  #=========================================================
  pod 'ChatKit', :path => '../'

  #=========================================================
  #======================== Demo Dependency ================
  #=========================================================

  pod 'CYLTabBarController', '1.9.0'
  pod 'TWMessageBarManager', '1.8.1'
  pod 'MLPAutoCompleteTextField', '1.5'
  pod 'FTPopOverMenu', '1.3.2'
  pod 'FXForms', '1.2.14'
end
