platform :ios , 7.0 
link_with 'LeanCloudChatKit-iOS', 'LeanCloudChatKit-iOSTests' 

#=========================================================
#======================== Lib Dependency ===================
#=========================================================
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'MJRefresh'
pod 'Masonry'
pod 'SDWebImage'
pod 'FMDB'
pod 'UITableView+FDTemplateLayoutCell'

#=========================================================
#======================== Demo Dependency ===================
#=========================================================

pod 'MBProgressHUD'
pod 'CYLTabBarController'
pod 'TWMessageBarManager'
pod "FDStackView", "1.0"
pod 'MWPhotoBrowser'
pod 'MLPAutoCompleteTextField'

#=========================================================
#======================== DELETE =========================
#=========================================================

#pod 'StitchingImage', :git => 'https://github.com/zhengjinghua/StitchingImage.git'
#pod 'NSData+MD5Digest'
#pod "Emoji", :git => 'https://github.com/jcccn/Emoji.git'
#pod 'FLAnimatedImage'
#pod 'SECoreTextView'
#pod "LKBadgeView", :git => 'https://github.com/lakesoft/LKBadgeView.git'
#pod 'YYKit'
#pod 'AWFileHash'